### ISSUE TITLE
PlaintextParser : TypeError

### ISSUE THREAD

**Issue by baruaranojoy** [miso-belica/sumy#119] opened 2019-01-20 16:49 UTC
```python
data = []
for sentence_ in summarizer(parser.document, SENTENCES_COUNT):
    data.append(str(sentence_))
```

gives `TypeError: 'module' object is not callable`
How to convert the `sentence_` to string for writing in a file?

**Comment by miso-belica** [comment] 2019-05-19 13:24
Hi @baruaranojoy, I updated [the example in README](https://github.com/miso-belica/sumy#python-api) with link to Wikipedia and it's working again :) I tried to reproduce your issue but I am not successful. I am afraid that without more code from you I am not able to help you. But from the error message, I guess that `summarizer` is imported module and not `Summarizer` object and that's the problem.

I am going to close it here, but the issue is really old (sorry for the so late reply) but if you still need help feel free to reopen it here with more info about your issue. Have a nice day :)

**Closed by miso-belica** 2019-05-19 13:24 UTC
