### ISSUE TITLE
Error with upper case sentence

### ISSUE THREAD

**Issue by CGNx** [miso-belica/sumy#16] opened 2014-12-09 15:28 UTC
The following string will throw an error when you try to summarize with any sentence count.
```py
string = 'YO! LONDON! WE'RE PLAYING THE ELECTRIC BALLBAG TONIGHT! COME HANG!'
```

To fix this, add the following to your repo:
```py
string = string.lower() if string.isupper() else string
```

**Comment by miso-belica** [comment] 2015-04-04 18:17
@CGNx I need more info about this. I'm not able to reproduce the issue so I'm closing it. Feel free to reopen and provide more info about how to reproduce it if this is still an issue for you.

**Closed by miso-belica** 2015-04-04 18:17 UTC
Labels: invalid
